### ISSUE TITLE
Collector coredumps (rarely) on FileFlow deletion from cache

### ISSUE THREAD

**Issue by terylt** [sysflow-telemetry/sf-docs#2]
**Indicate project**
collector

**Describe the bug**
When running a long load test on kubernetes, the collector coredumps with the following output:

```
DKMS: install completed.

Trying to load a dkms sysdig-probe, if present
sysdig-probe found and loaded in dkms
850346 [0x7f13c47dc8c0] ERROR sysflow.fileflow null - Cannot find FileFlow Object e540ed143053 in data flow set. Deleting. This should not happen.
free(): double free detected in tcache 2
Aborted (core dumped)
```
The error looks to be that a FileFlow is removed from the cache and freed twice. 

**To reproduce**
We have not to date been able to come up with a scenario that consistently causes this issue.  We have seen it at random times when collecting data in a load test of a nodejs server in the IBM cloud.   Will add more context to this issue as we get it.

I added a stacktrace printout to the location of the coredump and some more logging information in hopes to gather more information about the bug.

**Expected behavior**
Not to crash.

**Environment (please complete the following information):**
 - OS: IBM Cloud kube cluster.
 - SysFlow version: v0.1
 - Command line arguments and filters (if applicable): -f "container.type!=host and container.type=docker and container.name!=sfexporter and container.name!=sfcollector and container.name!=sftestharness and container.name!=skydive-agent" -w /mnt/data/mon -e test
 
 - Container orchestration framework and version (if applicable): kubernetes 1.13.12_1539
 - Container runtime (if applicable): docker

**Comment by araujof** [comment]
@terylpt have we observed this error since then? I have the impression this has been fixed when during our code review/linting sessions.
