### ISSUE TITLE
to add an option to export the logs to a file

### ISSUE THREAD

**Issue by mutazalsallal** [sysflow-telemetry/sf-docs#24]
**Indicate project**
sf-exporter

**Describe the feature you'd like**
it will be great to have an option to export the logs to a log file, it will help in troubleshooting, and offering more ways to get the sysflow output.

**Comment by zvn** [comment]
What's the log you mentioned about? It's the sysflow avro logs? Or the process debug logs(e.g. crash information)?

**Comment by mutazalsallal** [comment]
to export the sysflow avro logs in a json file, like /var/log/sysflow/audit.log

also, we will need to save the process debug logs(e.g. crash information)? or the stdout in a separate file
