### ISSUE TITLE
Network Sent/Receive event doesn't have the correct source IP/port

### ISSUE THREAD

**Issue by mutazalsallal** [sysflow-telemetry/sf-docs#26]
**Indicate project**
sf-collector

**Describe the bug**
the logged source IP/port is incorrect.

**To reproduce**
1. ping 9.9.9.9

**Expected behavior**
when executing the above ping request, the first logged event (connect) has the correct source and destination IP
the send/receive event has an incorrect source IP and source port.

those are the two logged events after executing the above ping command:

<13>Feb 18 14:32:20 ubuntu3 {"v": "0.1-rc3", "type": "NF", "state": "MODIFIED", "opflags": "  C     C  ", "opflags_bitmap": 1088, "ret": null, "ts": "02/18/2020T14:31:29.550138", "ts_uts": 1582036289550137646, "endts": "02/18/2020T14:31:29.550147", "endts_uts": 1582036289550147046, "proc.pid": 46279, "proc.tid": 46279, "proc.uid": 0, "proc.user": "root", "proc.gid": 0, "proc.group": "root", "proc.exe": "/bin/ping", "proc.args": "9.9.9.9", "proc.tty": true, "proc.createts": 1582036289547609214, "pproc.pid": 45782, "pproc.gid": 0, "pproc.uid": 0, "pproc.group": "root", "pproc.tty": true, "pproc.user": "root", "pproc.exe": "/bin/bash", "pproc.args": "", "pproc.createts": 1582032865869464898, "file.fd": 5, "file.path": "", "file.newpath": "", "file.openflags": "", "net.proto": 17, "net.sport": 52898, "net.dport": 1025, "net.sip": "192.168.0.193", "net.dip": "9.9.9.9", "res": "192.168.0.193:52898-9.9.9.9:1025", "flow.rbytes": 0, "flow.rops": 0, "flow.wbytes": 0, "flow.wops": 0, "container.id": "", "container.name": "", "container.imageid": "", "container.image": "", "container.type": "", "container.privileged": ""}

<13>Feb 18 14:32:20 ubuntu3 {"v": "0.1-rc3", "type": "NF", "state": "MODIFIED", "opflags": "   WR      ", "opflags_bitmap": 768, "ret": null, "ts": "02/18/2020T14:31:29.551366", "ts_uts": 1582036289551365862, "endts": "02/18/2020T14:31:59.020513", "endts_uts": 1582036319020513000, "proc.pid": 46279, "proc.tid": 46279, "proc.uid": 0, "proc.user": "root", "proc.gid": 0, "proc.group": "root", "proc.exe": "/bin/ping", "proc.args": "9.9.9.9", "proc.tty": true, "proc.createts": 1582036289547609214, "pproc.pid": 45782, "pproc.gid": 0, "pproc.uid": 0, "pproc.group": "root", "pproc.tty": true, "pproc.user": "root", "pproc.exe": "/bin/bash", "pproc.args": "", "pproc.createts": 1582032865869464898, "file.fd": 3, "file.path": "", "file.newpath": "", "file.openflags": "", "net.proto": 254, "net.sport": 1, "net.dport": 0, "net.sip": "172.17.0.2", "net.dip": "9.9.9.9", "res": "172.17.0.2:1-9.9.9.9:0", "flow.rbytes": 2520, "flow.rops": 30, "flow.wbytes": 1920, "flow.wops": 30, "container.id": "", "container.name": "", "container.imageid": "", "container.image": "", "container.type": "", "container.privileged": ""}

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Kernel: Linux 5.3.0-26-generic
 - Architecture: x86-64
 - SysFlow version: sf-collector:edge
 - Container runtime (if applicable): Docker

**Comment by mutazalsallal** [comment]
also how the net.proto changed from 17 to 254

**Comment by araujof** [comment]
Recall that the SysFlow collector doesn't track raw packets over the network interface, but system calls executions. So, effectively, what you see in this trace are network flows captured from the system calls executed by the ping/iputils process. For more details about what happen when you run ping (from a system call perspective), see: https://echorand.me/posts/my-own-ping/
