### ISSUE TITLE
how to know if a privileged container has been created

### ISSUE THREAD

**Issue by mutazalsallal** [sysflow-telemetry/sf-docs#36]
**Indicate project**
sf-apis, sf-collector

**Open Question**
how to know if a new privileged container has been created

**To reproduce**
docker run -it --privileged ubuntu bash

**Expected behavior**
to have an event or a way to know when a new container will be created
eg:
if vpid = 1 and container ID is not null and privileged = true

**Comment by araujof** [comment]
There is a `container.privileged` flag that indicates whether a container is privileged.
