### ISSUE TITLE
Exporter file descriptor leaks while exporting to syslog

### ISSUE THREAD

**Issue by COLDTURNIP** [sysflow-telemetry/sf-docs#43]
**Indicate project**
exporter

**Describe the bug**
Exporter stops reading collector output and possibility died shortly after being launched. This is caused by running out of file descriptors:

- avro readers are not closed after exported
- syslog logging handlers are created and appended in each exporting periods

**To reproduce**
1. produce bunch of avro output with sf-collector
2. launch exporter with very short exporting interval (`INTERVAL=0`) and keep watching logs
3. exporter stop works soon

**Expected behavior**
Exporter keep working until user sends termination signal to it.

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - SysFlow version: 0.1-rc3/edge
 - Command line arguments and filters (if applicable): N/A
 - Configurations (if applicable):
    - sf-collector `INTERVAL=1`
    - sf-exporter `INTERVAL=0`
 - Container orchestration framework and version (if applicable): N/A
 - Container runtime (if applicable): Docker

**Comment by araujof** [comment]
Fixed in https://github.com/sysflow-telemetry/sf-exporter/commit/e7ad9dead588634c8ddf85a9b7001e23063a6103
