### ISSUE TITLE
Notebooks in sf-apis/pynb fail on queries with 'prog.aname'

### ISSUE THREAD

**Issue by axeltanner** [sysflow-telemetry/sf-docs#44]
**Indicate project**
sf-apis

**Describe the bug**
Running pynb/FloConTutorialDemo.ipynb in the docker container raises errors in the 2 queries that use 'proc.aname'.
Replacing 'proc.aname' to 'proc.name' in cells 15 & 17 seems to give the expected behavior.
Similar for pynb/FloConTalkDemo.ipynb in cells 5 & 7.

**To reproduce**
1. docker run --rm -d --name sfnb --user $(id -u):$(id -g) --group-add users -v $(pwd)/pynb:/home/jovyan/work -p 8888:8888 sysflowtelemetry/sfnb
2. Connect to http://localhost:8888
3. Open pynb/FloConTutorialDemo.ipynb and pynb/FloConTalkDemo.ipynb
4. Run cells ...

**Expected behavior**
It should not give errors :-)

**Screenshots**
See cells 15 and 17 in:
![image](https://user-images.githubusercontent.com/61055409/85005564-4705f580-b159-11ea-94ac-1361036f6b15.png)

Fixed after using 'proc.name' instead:
![image](https://user-images.githubusercontent.com/61055409/85005734-7d437500-b159-11ea-8eb2-19241aa3607b.png)

**Environment (please complete the following information):**
All environment set by the docker image sysflowtelemetry/sfnb (as used 2020-06-18)

**Comment by araujof** [comment]
This bug has already been fixed in dev (`edge` tag).
