### ISSUE TITLE
Deployment needs to support OpenShift operator

### ISSUE THREAD

**Issue by terylt** [sysflow-telemetry/sf-docs#5]
**Indicate project**
sf-deployment

**Describe the feature you'd like**
Currently we only support a kubernetes helm chart to deploy the collector/exporter in the cloud.  In order to fully support OpenShift, we need to build an operator. 

**RFE**
https://github.com/sysflow-telemetry/sf-docs/wiki/RFE-Open-Shift-Operators

**sf-exporter tasks**
- [x] Build sf-exporter image from ubi7/python-36? image
- [x] Define operator for sf-exporter deployment

**sf-collector tasks**
- [x] Build sf-collector image from ubi7/ubi? image
- [x] Define operator for sf-collector deployment

**Comment by startxfr** [comment]
Do you plan to create a project for this operator. If it's already done coule toi provide the repo URL ? Thanks

**Comment by araujof** [comment]
Hi @startxfr, we are working on it. We will upload the RFE and git issues sometime this week.

**Comment by araujof** [comment]
OC Operator has been implemented and it's available in https://github.com/sysflow-telemetry/sf-deployments/tree/oc-operator. We are testing and polishing it and will merge it to master soon. 

We will be working on a separate issue to certify the operator with RedHat and IBM Cloud Pack for Security.
