### ISSUE TITLE
All exe and file paths should be absolute in SysFlow output

### ISSUE THREAD

**Issue by terylt** [sysflow-telemetry/sf-docs#6]
**Indicate project**
collector

**Describe the bug**
If a monitored process is launched using a relative path, that relative path will be reflected in the SysFlow output, rather than the absolute path.  

**To reproduce**
1. Setup sf-collector to monitor a host.
2. Execute an exe using a relative path.
3. Check the resulting SysFlow output.  You will see a relative path.

**Expected behavior**

Ideally, all EXE and file paths would be absolute for analysis purposes.

**Environment (please complete the following information):**
 - OS:  ubuntu 16.04-18.04
 - SysFlow version: v0.1 (Sysdig 0.24.2)
 

**Additional context**
This stems from an issue in the sysdig core which  provides an event attribute that is called m_exe, and one called m_exepath. If the exe monitored is launched using a relative path, m_exepath is blank, and m_exe only has the relative path. We need a way to load the absolute path.  Also note that the function `get_cwd()` is often blank, making it hard to recreate the absolute path.   We have not tried this with sysdig 0.26.4 - might be fixed.

**Comment by araujof** [comment]
We try to obtain the canonical path, when possible (best effort).
