### ISSUE TITLE
Filtering based on Entity/Flow/Event type

### ISSUE THREAD

**Issue by terylt** [sysflow-telemetry/sf-docs#7]
**Indicate project**
collector

**Describe the feature you'd like**
The collector should support filtering based on the object type (e.g., entity, NetworkFlow, FileFlow, etc.)  This would enable the collector to be tailored for specific types of analyzes.  Note that the collector currently supports sysdig's powerful filtering.

**Comment by araujof** [comment]
Implemented sysflow filtering as part of exporter/edge processing stack.
